'use strict';

/*
NOTE:
"Even Fibonacci numbers"
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

console.time("s");

let s = 0;
const FA = [];
let Fll = 0;
let Fl = 1;

while(Fl < 4000000) {
  const F = Fl + Fll;
  Fll = Fl;
  Fl = F;
  FA.push(F);
}

// Lose the last item as it's over our max
FA.pop();

// Iterate through terms and sum the even ones:
for (const i in FA) {
  const Ft = FA[i];
  // Check if it's even
  if(Ft % 2 === 0) {
    // Sum it:
    s += Ft;
  }
}

console.log(s);
console.timeEnd("s");
